// https://codeforces.com/blog/entry/47764
// https://codeforces.com/contest/453/problem/B

#include <iostream>
using namespace std;

//@ vars
const int nlim = 101;
const int blim = 60;
const int prim[] = {
	2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,	// generated by .algorithm.eratosthenes
};
int n, arr[nlim], dp[ ][ ];


//@ drivers
int main() {
	cin >> n;
	for (int i = 0; i < n; i++) cin >> arr[i];

	// returns
	system("pause");
	return 0;
}
